### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by agudulin** [amaslenn/git-sculpt#1]
Hi, Andrew!

This is a tool I was looking for 😎

It would be great to have an interactive mode, though:
```sh
$ git sculpt -i
> Going through all the branches...
> Feature branch: `feature/foo`
> Delete? [Y/n]
> Feature branch: `feature/bar`
> Delete? [Y/n]
# ...
```

or even YOLO mode:

```sh
$ git sculpt --yolo
> The following feature branches has been removed:
> ‣ `feature/foo`
> ‣ `feature/bar`
```

What do you think?

**Comment by amaslenn** [comment]
Great idea!
Walking through all local branches instead of one specified can replace interactive mode. What do you think? In addition tool may accept several branch name instead of one.

Could you please tell me more about `--yolo` mode? What is it? Seems like what I described about walking through all branches.

**Comment by agudulin** [comment]
As for me, interactive mode walks through all the local branches and asks you if you want to remove the branch, or not.
But `yolo` mode does not ask you anything, it *just does the job*: cleans everything up.

**Comment by amaslenn** [comment]
OK, so we have two features:
 - `--yolo` or more _git_ way `--all`, agree?
 - interactive mode which traverse thru all local branches asking you whether you want to remove it or not? Considering that removal is save.

Correct?

**Comment by agudulin** [comment]
Yes 🐨

**Comment by amaslenn** [comment]
OK, let's create two separate requests. I will do it later, or you can do it on your own :)

Thanks for feedback!

**Comment by amaslenn** [comment]
Created #2 and #3. Closing this one.
